# Generated by Django 5.0.6 on 2024-06-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tools',
            new_name='tools_and_languages',
        ),
    ]
