# Generated by Django 5.0.6 on 2024-06-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tools_project_tools_and_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
    ]
