# Generated by Django 5.0.6 on 2024-09-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bookcall_hireme'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcall',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hireme',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
